### ISSUE TITLE
Removal Candidate

### ISSUE THREAD

**Issue by Adurol** [KaOS-Community-Packages/hub#1]
This Package will be removed in 7 days from KCP.

Reason: **Broken**
`==> ERROR: A failure occurred in build().`

Please see also: [Using KaOS Community Packages](https://kaosx.us/phpBB3/viewtopic.php?f=12&t=145) and [KCP Guide](https://kaosx.us/kcp-guide/)

**Comment by bvaudour** [comment]
Corrected.
